  options:
    logging: CLOUD_LOGGING_ONLY
    pool: {}
  projectId: $PROJECT_ID
  steps:
  - name: gcr.io/k8s-skaffold/pack
    entrypoint: pack
    args:
    - build
    - $LOCATION-docker.pkg.dev/$PROJECT_ID/public-app/hellofunction
    - --builder
    - us-central1-docker.pkg.dev/serverless-runtimes/google-22-full/builder/python:public-image-current
    - --run-image
    - us-central1-docker.pkg.dev/serverless-runtimes/google-22/scratch/python312:public-image-next
    - --network
    - cloudbuild
  images:
  - '$LOCATION-docker.pkg.dev/$PROJECT_ID/public-app/hellofunction'